<?php

namespace Database\Seeders;

use App\Models\Event;
use App\Models\Travel;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class EventRespSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');
        Event::truncate();
        DB::statement('SET FOREIGN_KEY_CHECKS=1;');

        $events = [
            [
                'id' => 1,
                'title' => 'Visita San Luis de la Paz',
                'description' => 'Toma de fotografías para intranet',
                'date' => '2024-06-04',
                'available_seats' => 0,
                'empleado_id' => 80,
                'event_id' => null,
                'created_at' => '2024-06-04 20:21:40',
                'updated_at' => '2024-06-04 20:21:40',
            ],
            [
                'id' => 2,
                'title' => 'Toma de Fotografía corporativa / Entrevistas vendedores Lubricantes Irapuato',
                'description' => 'Atender entrevistas y fotografía a personal Agencia Irapuato',
                'date' => '2024-06-13',
                'available_seats' => 0,
                'empleado_id' => 80,
                'event_id' => null,
                'created_at' => '2024-06-12 21:45:45',
                'updated_at' => '2024-06-12 21:50:45',
            ],
            [
                'id' => 3,
                'title' => 'Toma de fotografías Corporativas Abasolo',
                'description' => 'Toma de Fotos / revisar configuración de checador',
                'date' => '2024-06-13',
                'available_seats' => 0,
                'empleado_id' => 80,
                'event_id' => null,
                'created_at' => '2024-06-12 21:49:33',
                'updated_at' => '2024-06-12 21:49:33',
            ],
            [
                'id' => 4,
                'title' => 'Toma de fotografías  Qro. Colorado / 5 de Feb.',
                'description' => 'Toma de fotografías y atender entrevista.',
                'date' => '2024-06-14',
                'available_seats' => 0,
                'empleado_id' => 80,
                'event_id' => null,
                'created_at' => '2024-06-12 21:52:28',
                'updated_at' => '2024-06-12 21:52:28',
            ],
            [
                'id' => 5,
                'title' => 'Toma de fotografías Silao / Maguey',
                'description' => 'Toma de Fotografías Silao / Maguey',
                'date' => '2024-06-11',
                'available_seats' => 0,
                'empleado_id' => 80,
                'event_id' => null,
                'created_at' => '2024-06-12 21:54:31',
                'updated_at' => '2024-06-12 21:54:31',
            ],
            [
                'id' => 6,
                'title' => 'Visita Silao-El Maguey',
                'description' => 'Actividades laborales y entrevista',
                'date' => '2024-06-19',
                'available_seats' => 0,
                'empleado_id' => 80,
                'event_id' => null,
                'created_at' => '2024-06-14 21:10:58',
                'updated_at' => '2024-06-14 21:10:58',
            ],
            [
                'id' => 7,
                'title' => 'Visita Qro. 5 de Feb.',
                'description' => 'Revisión de tema laboral',
                'date' => '2024-06-21',
                'available_seats' => 0,
                'empleado_id' => 80,
                'event_id' => null,
                'created_at' => '2024-06-14 21:19:48',
                'updated_at' => '2024-06-19 18:31:24',
            ],
            [
                'id' => 12,
                'title' => 'Tema Laboral Acambaro',
                'description' => 'Atención te tema laboral',
                'date' => '2024-06-20',
                'available_seats' => 0,
                'empleado_id' => 80,
                'event_id' => null,
                'created_at' => '2024-06-20 22:29:25',
                'updated_at' => '2024-06-20 22:29:25',
            ],
            [
                'id' => 13,
                'title' => 'Visita mantenimiento Silao',
                'description' => 'Visita a sucursal para realizar mantenimientos preventivos a los equipos de cómputo.',
                'date' => '2024-07-02',
                'available_seats' => 0,
                'empleado_id' => 251,
                'event_id' => null,
                'created_at' => '2024-06-21 14:24:04',
                'updated_at' => '2024-06-21 14:29:05',
            ],
            [
                'id' => 14,
                'title' => 'Visita mantenimiento Silao',
                'description' => 'Visita a sucursal para realizar mantenimientos preventivos a los equipos de cómputo.',
                'date' => '2024-07-03',
                'available_seats' => 0,
                'empleado_id' => 251,
                'event_id' => null,
                'created_at' => '2024-06-21 14:24:04',
                'updated_at' => '2024-06-21 14:29:05',
            ],
            [
                'id' => 15,
                'title' => 'Visita mantenimiento Silao',
                'description' => 'Visita a sucursal para realizar mantenimientos preventivos a los equipos de cómputo.',
                'date' => '2024-07-04',
                'available_seats' => 0,
                'empleado_id' => 251,
                'event_id' => null,
                'created_at' => '2024-06-21 14:30:58',
                'updated_at' => '2024-06-21 14:30:58',
            ],
            [
                'id' => 16,
                'title' => 'Visita mantenimiento Querétaro',
                'description' => 'Visita a sucursal para realizar mantenimientos preventivos a los equipos de cómputo.',
                'date' => '2024-07-16',
                'available_seats' => 0,
                'empleado_id' => 251,
                'event_id' => null,
                'created_at' => '2024-06-21 15:02:17',
                'updated_at' => '2024-06-21 15:02:17',
            ],
            [
                'id' => 17,
                'title' => 'Visita mantenimiento Quéretaro',
                'description' => 'Visita a sucursal para realizar mantenimientos preventivos a los equipos de cómputo.',
                'date' => '2024-07-17',
                'available_seats' => 0,
                'empleado_id' => 251,
                'event_id' => null,
                'created_at' => '2024-06-21 15:02:57',
                'updated_at' => '2024-06-21 15:02:57',
            ],
            [
                'id' => 18,
                'title' => 'Visita mantenimiento Quéretaro',
                'description' => 'Visita a sucursal para realizar mantenimientos preventivos a los equipos de cómputo.',
                'date' => '2024-07-18',
                'available_seats' => 0,
                'empleado_id' => 251,
                'event_id' => null,
                'created_at' => '2024-06-21 15:03:30',
                'updated_at' => '2024-06-21 15:03:30',
            ],
            [
                'id' => 19,
                'title' => 'Visita mantenimiento Quéretaro',
                'description' => 'Visita a sucursal para realizar mantenimientos preventivos a los equipos de cómputo.',
                'date' => '2024-07-23',
                'available_seats' => 0,
                'empleado_id' => 251,
                'event_id' => null,
                'created_at' => '2024-06-21 15:03:58',
                'updated_at' => '2024-06-21 15:03:58',
            ],
            [
                'id' => 20,
                'title' => 'SUCURSAL CELAYA',
                'description' => 'REVISON FACTURACION',
                'date' => '2024-06-24',
                'available_seats' => 0,
                'empleado_id' => 222,
                'event_id' => null,
                'created_at' => '2024-06-22 18:37:54',
                'updated_at' => '2024-06-22 18:37:54',
            ],
            [
                'id' => 21,
                'title' => 'REUNION',
                'description' => 'REUNION CP MAYRA',
                'date' => '2024-06-26',
                'available_seats' => 0,
                'empleado_id' => 222,
                'event_id' => null,
                'created_at' => '2024-06-22 18:38:34',
                'updated_at' => '2024-06-22 18:38:34',
            ],
            [
                'id' => 22,
                'title' => 'Visita de Recursos Humanos',
                'description' => 'Revisión de temas laborales varios',
                'date' => '2024-07-03',
                'available_seats' => 0,
                'empleado_id' => 80,
                'event_id' => null,
                'created_at' => '2024-06-26 19:53:12',
                'updated_at' => '2024-06-26 19:53:12',
            ],
            [
                'id' => 23,
                'title' => 'Visita Qro. Colorado',
                'description' => 'Actividades varias',
                'date' => '2024-07-01',
                'available_seats' => 0,
                'empleado_id' => 80,
                'event_id' => null,
                'created_at' => '2024-06-29 16:03:03',
                'updated_at' => '2024-06-29 16:03:03',
            ],
            [
                'id' => 24,
                'title' => 'Visita San Luis de la Paz',
                'description' => 'Asignación de tareas adicionales personal de refacciones',
                'date' => '2024-07-02',
                'available_seats' => 0,
                'event_id' => null,
                'empleado_id' => 80,
                'created_at' => '2024-06-29 16:06:19',
                'updated_at' => '2024-06-29 16:06:19',
            ],
            [
                'id' => 25,
                'title' => 'Visita Silao y El Maguey',
                'description' => null,
                'date' => '2024-07-04',
                'available_seats' => 0,
                'event_id' => null,
                'empleado_id' => 80,
                'created_at' => '2024-06-29 18:21:12',
                'updated_at' => '2024-06-29 18:21:12',
            ],
            [
                'id' => 26,
                'title' => 'Visita Irapuato',
                'description' => null,
                'date' => '2024-07-08',
                'available_seats' => 0,
                'event_id' => null,
                'empleado_id' => 80,
                'created_at' => '2024-06-29 18:22:04',
                'updated_at' => '2024-06-29 18:22:04',
            ],
            [
                'id' => 27,
                'title' => 'REVISION',
                'description' => null,
                'date' => '2024-07-01',
                'available_seats' => 0,
                'event_id' => null,
                'empleado_id' => 222,
                'created_at' => '2024-07-01 14:13:00',
                'updated_at' => '2024-07-01 14:13:00',
            ],
            [
                'id' => 28,
                'title' => 'REVISION',
                'description' => 'FACTURACION',
                'date' => '2024-07-02',
                'available_seats' => 0,
                'event_id' => null,
                'empleado_id' => 222,
                'created_at' => '2024-07-01 14:14:22',
                'updated_at' => '2024-07-01 14:14:22',
            ],
            [
                'id' => 29,
                'title' => 'VISITA',
                'description' => 'FACTURACION',
                'date' => '2024-07-03',
                'available_seats' => 0,
                'event_id' => null,
                'empleado_id' => 222,
                'created_at' => '2024-07-01 14:15:27',
                'updated_at' => '2024-07-01 14:15:27',
            ],
            [
                'id' => 30,
                'title' => 'VISITA',
                'description' => 'INVENTARIO',
                'date' => '2024-07-04',
                'available_seats' => 0,
                'event_id' => null,
                'empleado_id' => 222,
                'created_at' => '2024-07-01 14:15:59',
                'updated_at' => '2024-07-01 14:17:44',
            ],
            [
                'id' => 31,
                'title' => 'VISITA',
                'description' => 'INVENTARIO',
                'date' => '2024-07-05',
                'available_seats' => 0,
                'event_id' => null,
                'empleado_id' => 222,
                'created_at' => '2024-07-01 14:16:30',
                'updated_at' => '2024-07-01 14:16:30',
            ],
            [
                'id' => 32,
                'title' => 'VISITA',
                'description' => 'REVISION FACTURACION',
                'date' => '2024-07-06',
                'available_seats' => 0,
                'event_id' => null,
                'empleado_id' => 222,
                'created_at' => '2024-07-01 14:17:19',
                'updated_at' => '2024-07-01 14:17:19',
            ],
            [
                'id' => 34,
                'title' => 'REVISION LISTA DE PRECIOS',
                'description' => null,
                'date' => '2024-07-01',
                'available_seats' => 0,
                'event_id' => null,
                'empleado_id' => 83,
                'created_at' => '2024-07-01 16:49:39',
                'updated_at' => '2024-07-01 16:49:39',
            ],
            [
                'id' => 35,
                'title' => 'JUNTA CON JESUS SANTIAGO',
                'description' => null,
                'date' => '2024-07-02',
                'available_seats' => 0,
                'event_id' => null,
                'empleado_id' => 83,
                'created_at' => '2024-07-01 16:50:43',
                'updated_at' => '2024-07-02 14:11:37',
            ],
            [
                'id' => 36,
                'title' => 'VISITA CLIENTE MICSA',
                'description' => null,
                'date' => '2024-07-03',
                'available_seats' => 0,
                'event_id' => null,
                'empleado_id' => 83,
                'created_at' => '2024-07-01 16:52:21',
                'updated_at' => '2024-07-02 14:12:21',
            ],
            [
                'id' => 37,
                'title' => 'Junta de apertura',
                'description' => 'Auditoria Orden y limpieza',
                'date' => '2024-07-04',
                'available_seats' => 0,
                'event_id' => null,
                'empleado_id' => 79,
                'created_at' => '2024-07-01 16:53:46',
                'updated_at' => '2024-07-01 16:54:20',
            ],
            [
                'id' => 38,
                'title' => 'Junta de Apertura',
                'description' => 'Auditoria Orden y limpieza Qro',
                'date' => '2024-07-01',
                'available_seats' => 0,
                'event_id' => null,
                'empleado_id' => 79,
                'created_at' => '2024-07-01 16:56:12',
                'updated_at' => '2024-07-01 16:56:12',
            ],
            [
                'id' => 39,
                'title' => 'REVISION DEL CONTRATO SIAP',
                'description' => 'GENERAR ORDEN DE COMPRA DEL BULLDOZER QUE SE COMPRARA A MAQRO EN SUSTITUCION DEL ROBADO',
                'date' => '2024-07-04',
                'available_seats' => 0,
                'event_id' => null,
                'empleado_id' => 83,
                'created_at' => '2024-07-01 17:00:35',
                'updated_at' => '2024-07-04 18:24:49',
            ],
            [
                'id' => 41,
                'title' => 'SEGUIMIENTO A PROSPECTOS',
                'description' => null,
                'date' => '2024-07-05',
                'available_seats' => 0,
                'event_id' => null,
                'empleado_id' => 83,
                'created_at' => '2024-07-01 17:02:39',
                'updated_at' => '2024-07-01 17:02:39',
            ],
            [
                'id' => 42,
                'title' => 'REVISION DE PAPGO DE RENTAS',
                'description' => null,
                'date' => '2024-07-06',
                'available_seats' => 0,
                'event_id' => null,
                'empleado_id' => 83,
                'created_at' => '2024-07-01 17:04:22',
                'updated_at' => '2024-07-01 17:04:22',
            ],
            [
                'id' => 43,
                'title' => 'Junta de apertura',
                'description' => 'Auditoria Orden y limpieza',
                'date' => '2024-07-08',
                'available_seats' => 0,
                'event_id' => null,
                'empleado_id' => 79,
                'created_at' => '2024-07-01 17:08:15',
                'updated_at' => '2024-07-01 17:08:15',
            ],
            [
                'id' => 44,
                'title' => 'REVISION DE VENTAS',
                'description' => 'REVISAR LAS OPERACIONES Y SU VIABILIDAD EN LA SUCURSAL',
                'date' => '2024-07-01',
                'available_seats' => 0,
                'event_id' => null,
                'empleado_id' => 82,
                'created_at' => '2024-07-01 17:20:16',
                'updated_at' => '2024-07-01 17:20:16',
            ],
            [
                'id' => 45,
                'title' => 'REVISION DE OPERACIONES',
                'description' => 'REVISAR LAS OPERACIONES Y SU VIABILIDAD EN LA SUCURSAL',
                'date' => '2024-07-02',
                'available_seats' => 0,
                'event_id' => null,
                'empleado_id' => 82,
                'created_at' => '2024-07-01 17:23:08',
                'updated_at' => '2024-07-01 17:23:08',
            ],
            [
                'id' => 46,
                'title' => 'REVISION DE OPERACIONES Y DEMOSTRACION DE DRON',
                'description' => 'REVISAR LAS OPERACIONES Y SU VIABILIDAD EN LA SUCURSAL Y DEMOSTRACION DE DRONES A ULISES BANDA',
                'date' => '2024-07-02',
                'available_seats' => 0,
                'event_id' => null,
                'empleado_id' => 82,
                'created_at' => '2024-07-01 17:24:07',
                'updated_at' => '2024-07-01 17:24:07',
            ],
            [
                'id' => 47,
                'title' => 'VISITA CELAYA',
                'description' => 'REVISAR LAS OPERACIONES Y SU VIABILIDAD EN LA SUCURSAL',
                'date' => '2024-07-03',
                'available_seats' => 0,
                'event_id' => null,
                'empleado_id' => 82,
                'created_at' => '2024-07-01 17:25:28',
                'updated_at' => '2024-07-01 17:25:28',
            ],
            [
                'id' => 48,
                'title' => 'VISITA A SAN LUIS DE LA PAZ',
                'description' => 'COORDINACON EVENTO DEMOSTRACION',
                'date' => '2024-07-04',
                'available_seats' => 0,
                'event_id' => null,
                'empleado_id' => 82,
                'created_at' => '2024-07-01 17:27:27',
                'updated_at' => '2024-07-01 17:27:27',
            ],
            [
                'id' => 49,
                'title' => 'VISITA A SILAO',
                'description' => 'REVISAR LAS OPERACIONES Y SU VIABILIDAD EN LA SUCURSAL',
                'date' => '2024-07-05',
                'available_seats' => 0,
                'event_id' => null,
                'empleado_id' => 82,
                'created_at' => '2024-07-01 17:28:28',
                'updated_at' => '2024-07-01 17:28:28',
            ],
            [
                'id' => 50,
                'title' => 'VISITA A QUERETARO',
                'description' => 'CAPACITACION ERICK AMEALCO',
                'date' => '2024-07-06',
                'available_seats' => 0,
                'event_id' => null,
                'empleado_id' => 82,
                'created_at' => '2024-07-01 17:29:48',
                'updated_at' => '2024-07-01 17:29:48',
            ],
            [
                'id' => 51,
                'title' => 'DEMOSTACION DOLORES HIDALGO',
                'description' => 'REALIZACION DE DEMOSTRACION T50 Y 6803',
                'date' => '2024-07-11',
                'available_seats' => 0,
                'event_id' => null,
                'empleado_id' => 82,
                'created_at' => '2024-07-01 17:31:57',
                'updated_at' => '2024-07-01 17:31:57',
            ],
            [
                'id' => 52,
                'title' => 'VISITA 5 DE FEBRERO',
                'description' => null,
                'date' => '2024-07-01',
                'available_seats' => 0,
                'event_id' => null,
                'empleado_id' => 85,
                'created_at' => '2024-07-01 19:01:28',
                'updated_at' => '2024-07-01 19:01:28',
            ],
            [
                'id' => 53,
                'title' => 'VISITA SILAO',
                'description' => 'CAPACITACION REFACCIONES. PASO A SUC SALAMANCA Y SUC IRAPUATO A DEJAR Y LLEVAR TRASPASOS (IDA Y VUELTA).',
                'date' => '2024-07-02',
                'available_seats' => 0,
                'event_id' => null,
                'empleado_id' => 85,
                'created_at' => '2024-07-01 19:04:16',
                'updated_at' => '2024-07-01 19:06:43',
            ],
            [
                'id' => 54,
                'title' => 'VISITA SUC SILAO',
                'description' => 'CAPACITACION REFACCIONES. PASO A SUC SALAMANCA Y SUC IRAPUATO A DEJAR Y LLEVAR TRASPASOS (IDA Y VUELTA).',
                'date' => '2024-07-04',
                'available_seats' => 0,
                'event_id' => null,
                'empleado_id' => 85,
                'created_at' => '2024-07-01 19:07:50',
                'updated_at' => '2024-07-01 19:08:07',
            ],
            [
                'id' => 55,
                'title' => 'VISITA SUC ACAMBARO',
                'description' => 'REFACCIONES',
                'date' => '2024-07-05',
                'available_seats' => 0,
                'event_id' => null,
                'empleado_id' => 85,
                'created_at' => '2024-07-01 19:11:23',
                'updated_at' => '2024-07-01 19:11:23',
            ],
            [
                'id' => 56,
                'title' => 'SUC CELAYA',
                'description' => null,
                'date' => '2024-07-03',
                'available_seats' => 0,
                'event_id' => null,
                'empleado_id' => 85,
                'created_at' => '2024-07-01 19:12:36',
                'updated_at' => '2024-07-01 19:12:36',
            ],
            [
                'id' => 57,
                'title' => 'SUC CELAYA',
                'description' => null,
                'date' => '2024-07-06',
                'available_seats' => 0,
                'event_id' => null,
                'empleado_id' => 85,
                'created_at' => '2024-07-01 19:12:59',
                'updated_at' => '2024-07-06 15:17:05',
            ],
            [
                'id' => 58,
                'title' => 'Revisión semanal de Asesores de ventas',
                'description' => 'Base Irapuato cupo lleno',
                'date' => '2024-07-01',
                'available_seats' => 0,
                'event_id' => null,
                'empleado_id' => 86,
                'created_at' => '2024-07-01 19:19:22',
                'updated_at' => '2024-07-01 19:19:22',
            ],
            [
                'id' => 59,
                'title' => 'VISITA SUC SALAMANCA',
                'description' => 'REUNION TEMAS FISCALES',
                'date' => '2024-07-01',
                'available_seats' => 0,
                'event_id' => null,
                'empleado_id' => 81,
                'created_at' => '2024-07-01 20:12:22',
                'updated_at' => '2024-07-01 20:12:22',
            ],
            [
                'id' => 60,
                'title' => 'Reunion',
                'description' => 'Reunión temas fiscales',
                'date' => '2024-07-01',
                'available_seats' => 0,
                'event_id' => null,
                'empleado_id' => 307,
                'created_at' => '2024-07-01 20:13:48',
                'updated_at' => '2024-07-01 20:13:48',
            ],
            [
                'id' => 61,
                'title' => 'BASE CELAYA',
                'description' => 'BASE CELAYA SI NECESITAN RAITE SALGO DE SALAMANCA 7.20 FAVOR DE MANDAR MENSAJE',
                'date' => '2024-07-02',
                'available_seats' => 0,
                'event_id' => null,
                'empleado_id' => 81,
                'created_at' => '2024-07-01 20:16:35',
                'updated_at' => '2024-07-01 20:23:30',
            ],
            [
                'id' => 62,
                'title' => 'BASE CELAYA',
                'description' => 'BASE CELAYA SI NECESITAN RAITE SALGO DE SALAMANCA 7.20 FAVOR DE MANDAR MENSAJE',
                'date' => '2024-07-03',
                'available_seats' => 0,
                'event_id' => null,
                'empleado_id' => 81,
                'created_at' => '2024-07-01 20:17:48',
                'updated_at' => '2024-07-01 20:24:00',
            ],
            [
                'id' => 63,
                'title' => 'BASE CELAYA',
                'description' => 'BASE CELAYA SI NECESITAN RAITE SALGO DE SALAMANCA 7.20 FAVOR DE MANDAR MENSAJE',
                'date' => '2024-07-04',
                'available_seats' => 0,
                'event_id' => null,
                'empleado_id' => 81,
                'created_at' => '2024-07-01 20:18:43',
                'updated_at' => '2024-07-01 20:24:20',
            ],
            [
                'id' => 64,
                'title' => 'BASE CELAYA',
                'description' => 'BASE CELAYA SI NECESITAN RAITE SALGO DE SALAMANCA 7.20 FAVOR DE MANDAR MENSAJE',
                'date' => '2024-07-05',
                'available_seats' => 0,
                'event_id' => null,
                'empleado_id' => 81,
                'created_at' => '2024-07-01 20:19:20',
                'updated_at' => '2024-07-01 20:24:43',
            ],
            [
                'id' => 65,
                'title' => 'BASE IRAPUATO',
                'description' => 'BASE IRAPUATO (REV PENDIENTES) SI NECESITAN RAITE SALGO DE SALAMANCA 7.30 FAVOR DE MANDAR MENSAJE',
                'date' => '2024-07-06',
                'available_seats' => 0,
                'event_id' => null,
                'empleado_id' => 81,
                'created_at' => '2024-07-01 20:20:29',
                'updated_at' => '2024-07-01 20:25:20',
            ],
            [
                'id' => 66,
                'title' => 'REUNION CELAYA',
                'description' => 'CURSO',
                'date' => '2024-07-11',
                'empleado_id' => 81,
                'created_at' => '2024-07-01 20:21:41',
                'updated_at' => '2024-07-01 20:21:41',
                'event_id' => null,
                'available_seats' => 0,
            ],
            [
                'id' => 67,
                'title' => 'Reunión',
                'description' => 'Resultados',
                'date' => '2024-07-01',
                'empleado_id' => 247,
                'created_at' => '2024-07-01 21:54:57',
                'updated_at' => '2024-07-01 21:54:57',
                'event_id' => null,
                'available_seats' => 0,
            ],
            [
                'id' => 68,
                'title' => 'Conciliaciones Contables',
                'description' => NULL,
                'date' => '2024-07-02',
                'empleado_id' => 247,
                'created_at' => '2024-07-01 21:59:49',
                'updated_at' => '2024-07-01 21:59:49',
                'event_id' => null,
                'available_seats' => 0,
            ],
            [
                'id' => 69,
                'title' => 'Conciliaciones Contables',
                'description' => NULL,
                'date' => '2024-07-03',
                'empleado_id' => 247,
                'created_at' => '2024-07-01 22:02:16',
                'updated_at' => '2024-07-01 22:02:16',
                'event_id' => null,
                'available_seats' => 0,
            ],
            [
                'id' => 70,
                'title' => 'Junta',
                'description' => 'Auto Evaluación Dealer Capabilities',
                'date' => '2024-07-05',
                'empleado_id' => 79,
                'created_at' => '2024-07-03 19:16:40',
                'updated_at' => '2024-07-03 19:16:40',
                'event_id' => null,
                'available_seats' => 0,
            ],
            [
                'id' => 71,
                'title' => 'Primera auditoria Suc Salamanca',
                'description' => 'Primer auditoria Orden y limpieza Salamanca',
                'date' => '2024-07-06',
                'empleado_id' => 79,
                'created_at' => '2024-07-03 19:17:33',
                'updated_at' => '2024-07-03 19:17:33',
                'event_id' => null,
                'available_seats' => 0,
            ],
            [
                'id' => 72,
                'title' => 'COLORADO',
                'description' => NULL,
                'date' => '2024-07-08',
                'empleado_id' => 85,
                'created_at' => '2024-07-06 16:52:01',
                'updated_at' => '2024-07-06 16:52:01',
                'event_id' => null,
                'available_seats' => 0,
            ],
            [
                'id' => 73,
                'title' => 'CAPACITACION REFACCIONES',
                'description' => 'PASO A SUC SALAMANCA E IRAPUATO IDA Y VUELTA POR TRASPASOS.',
                'date' => '2024-07-09',
                'empleado_id' => 85,
                'created_at' => '2024-07-06 16:53:44',
                'updated_at' => '2024-07-06 16:53:44',
                'event_id' => null,
                'available_seats' => 0,
            ],
            [
                'id' => 74,
                'title' => 'CAPACITACION REFACCIONES',
                'description' => 'PASO A SUC SALAMANCA E IRAPUATO IDA Y VUELTA POR TRASPASOS.',
                'date' => '2024-07-11',
                'empleado_id' => 85,
                'created_at' => '2024-07-06 16:54:27',
                'updated_at' => '2024-07-06 16:54:27',
                'event_id' => null,
                'available_seats' => 0,
            ],
            [
                'id' => 75,
                'title' => 'SUC SALAMANCA',
                'description' => 'REVISION ALTA CUENTAS STIHL',
                'date' => '2024-07-12',
                'empleado_id' => 85,
                'created_at' => '2024-07-06 16:55:28',
                'updated_at' => '2024-07-06 16:55:28',
                'event_id' => null,
                'available_seats' => 0,
            ],
            [
                'id' => 76,
                'title' => 'SUC CELAYA',
                'description' => NULL,
                'date' => '2024-07-10',
                'empleado_id' => 85,
                'created_at' => '2024-07-06 16:55:47',
                'updated_at' => '2024-07-06 16:55:47',
                'event_id' => null,
                'available_seats' => 0,
            ],
            [
                'id' => 77,
                'title' => 'SUC CELAYA',
                'description' => NULL,
                'date' => '2024-07-13',
                'empleado_id' => 85,
                'created_at' => '2024-07-06 16:56:06',
                'updated_at' => '2024-07-06 16:56:06',
                'event_id' => null,
                'available_seats' => 0,
            ],
            [
                'id' => 78,
                'title' => 'CAPACITACION REFACCIONES',
                'description' => 'PASO A SUC SALAMANCA E IRAPUATO IDA Y VUELTA POR TRASPASOS.',
                'date' => '2024-07-16',
                'empleado_id' => 85,
                'created_at' => '2024-07-06 16:57:00',
                'updated_at' => '2024-07-06 16:57:00',
                'event_id' => null,
                'available_seats' => 0,
            ],
            [
                'id' => 79,
                'title' => 'CAPACITACION REFACCIONES',
                'description' => 'PASO A SUC SALAMANCA E IRAPUATO IDA Y VUELTA POR TRASPASOS.',
                'date' => '2024-07-18',
                'empleado_id' => 85,
                'created_at' => '2024-07-06 16:57:27',
                'updated_at' => '2024-07-06 16:57:27',
                'event_id' => null,
                'available_seats' => 0,
            ],
            [
                'id' => 80,
                'title' => 'REVISION',
                'description' => 'CONTROLISTA',
                'date' => '2024-07-08',
                'empleado_id' => 222,
                'created_at' => '2024-07-08 15:02:41',
                'updated_at' => '2024-07-08 15:02:41',
                'event_id' => null,
                'available_seats' => 0,
            ],
            [
                'id' => 81,
                'title' => 'REVISION',
                'description' => 'CONTROLISTA',
                'date' => '2024-07-09',
                'empleado_id' => 222,
                'created_at' => '2024-07-08 15:03:21',
                'updated_at' => '2024-07-08 15:03:21',
                'event_id' => null,
                'available_seats' => 0,
            ],
            [
                'id' => 82,
                'title' => 'REVISION',
                'description' => 'CONTROLISTA',
                'date' => '2024-07-10',
                'empleado_id' => 222,
                'created_at' => '2024-07-08 15:04:01',
                'updated_at' => '2024-07-08 15:04:01',
                'event_id' => null,
                'available_seats' => 0,
            ],
            [
                'id' => 83,
                'title' => 'REVISION',
                'description' => 'CONTROLISTA',
                'date' => '2024-07-11',
                'empleado_id' => 222,
                'created_at' => '2024-07-08 15:05:10',
                'updated_at' => '2024-07-08 15:05:10',
                'event_id' => null,
                'available_seats' => 0,
            ],
            [
                'id' => 84,
                'title' => 'REVISION',
                'description' => 'CONTROLISTA',
                'date' => '2024-07-12',
                'empleado_id' => 222,
                'created_at' => '2024-07-08 15:05:51',
                'updated_at' => '2024-07-08 15:05:51',
                'event_id' => null,
                'available_seats' => 0,
            ],
            [
                'id' => 85,
                'title' => 'REVISION IRAPUATO',
                'description' => 'COMPRAS Y FACTURACION',
                'date' => '2024-07-13',
                'empleado_id' => 222,
                'created_at' => '2024-07-08 15:06:47',
                'updated_at' => '2024-07-08 15:06:47',
                'event_id' => null,
                'available_seats' => 0,
            ],
            [
                'id' => 86,
                'title' => 'SEGUIMIENTO A REPORTES DE PLAANTA/JUNTA CON ALEJANDRO JACOBO/BARAJAS/EMILIO',
                'description' => 'REVISION GANADAS Y PERDIDAS REPORTE A PLANTA',
                'event_id' => null,
                'available_seats' => 0,
                'date' => '2024-07-08',
                'empleado_id' => 83,
                'created_at' => '2024-07-08 15:36:17',
                'updated_at' => '2024-07-08 15:50:55',
            ],
            [
                'id' => 87,
                'title' => 'VISITA AGENCIA SALAMANCA',
                'description' => 'SUPERVISAR PROSPECCION DE LA AGENCIA',
                'event_id' => null,
                'available_seats' => 0,
                'date' => '2024-07-08',
                'empleado_id' => 83,
                'created_at' => '2024-07-08 15:38:59',
                'updated_at' => '2024-07-08 15:38:59',
            ],
            [
                'id' => 88,
                'title' => 'SEGUIMIENTO PROSPECTOS EQUIPO DE VENTAS SILAO',
                'description' => 'SEGUIMIENTO PROSPECTOS EQUIPO DE VENTAS SILAO',
                'event_id' => null,
                'available_seats' => 0,
                'date' => '2024-07-09',
                'empleado_id' => 83,
                'created_at' => '2024-07-08 15:40:46',
                'updated_at' => '2024-07-08 15:40:46',
            ],
            [
                'id' => 89,
                'title' => 'VISITA MICSA/REVISION DE PROSPECTOS/BENJAMIN/HERIBERTO/ERICK',
                'description' => 'CIERRE DE VENTA DE EQUIPOS EN RENTA',
                'event_id' => null,
                'available_seats' => 0,
                'date' => '2024-07-10',
                'empleado_id' => 83,
                'created_at' => '2024-07-08 15:41:46',
                'updated_at' => '2024-07-08 15:52:19',
            ],
            [
                'id' => 90,
                'title' => 'CURSO INTERNO FINANZAS',
                'description' => 'CURSO INTERNO FINANZAS',
                'event_id' => null,
                'available_seats' => 0,
                'date' => '2024-07-11',
                'empleado_id' => 83,
                'created_at' => '2024-07-08 15:43:27',
                'updated_at' => '2024-07-08 15:43:27',
            ],
            [
                'id' => 91,
                'title' => 'VISITA IRAPUATO',
                'description' => 'SEGUIMIENTO PROSPECCION',
                'event_id' => null,
                'available_seats' => 0,
                'date' => '2024-07-11',
                'empleado_id' => 83,
                'created_at' => '2024-07-08 15:45:16',
                'updated_at' => '2024-07-08 15:53:00',
            ],
            [
                'id' => 92,
                'title' => 'PLANEACION DE CURSOS PARA VENDEDORES',
                'description' => 'PLANEACION DE CURSOS PARA VENDEDORES',
                'event_id' => null,
                'available_seats' => 0,
                'date' => '2024-07-12',
                'empleado_id' => 83,
                'created_at' => '2024-07-08 15:47:59',
                'updated_at' => '2024-07-08 15:47:59',
            ],
            [
                'id' => 93,
                'title' => 'SUC. SILAO',
                'description' => 'SUC. SILAO',
                'event_id' => null,
                'available_seats' => 0,
                'date' => '2024-07-13',
                'empleado_id' => 83,
                'created_at' => '2024-07-08 15:49:52',
                'updated_at' => '2024-07-08 15:49:52',
            ],
        ];

        // Insertar los eventos en la base de datos
        DB::table('events')->insert($events);

    }
}
